default: &default
  adapter: mysql2
  pool: 5 
  timeout: 5000 

development:
  <<: *default
  database: test_project
  encoding: utf8
  username: <%= ENV["DEVLEOPMENT_USERNAME"] %>
  password: <%= ENV["DEVLEOPMENT_PASSWORD"] %>
  host: localhost

test:
  <<: *default
  database: test_test_project
  encoding: utf8
  username: <%= ENV["TEST_USERNAME"] %>
  password: <%= ENV["TEST_PASSWORD"] %>
  host: localhost
